# Generated by Django 4.0.4 on 2022-11-03 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_publications_article'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='publications',
            new_name='Publication',
        ),
    ]
